### ISSUE TITLE
add footer with social links

### ISSUE THREAD

**Issue by Bhavishya2601** [Starx-Quantum/Starxer-EditorX#6]
there is no footer
i would like to work on it under hactoberfest

**Comment by naitikhoriya1** [comment]
> there is no footer i would like to work on it under hactoberfest

create and create pull req

**Comment by Bhavishya2601** [comment]
Assign this issue to me

**Comment by Gurudutta22** [comment]
assign this issue to me

**Comment by Gurudutta22** [comment]
create pull request
